### ISSUE TITLE
Possible copy paste bug in CLIPPreprocessor

### ISSUE THREAD

**Issue by ahasselbring** [NaoDevils/CodeRelease#1]
https://github.com/NaoDevils/CodeRelease2016/blob/master/Src/Modules/Perception/CLIP/CLIPPreprocessor.h#L238
https://github.com/NaoDevils/CodeRelease2016/blob/master/Src/Modules/Perception/CLIP/CLIPPreprocessor.h#L244
Is it intended that the second difference is cr - cb and not cr - cr?

**Comment by schwingmar** [comment]
You are right, it is not as intended. It is already fixed in our current code, but was not correct during RoboCup (base for the release). The vision system worked in Leipzig regardless. I will just change this though since it is obviously not as it should be.
